dist: xenial

language: cpp

compiler:
  - gcc

install:
  - sudo apt-get install libboost-system-dev libboost-test-dev libboost-thread-dev cmake python-pip
  - sudo pip install -U cpp-coveralls

before_script:
  - mkdir build

script:
  - (cd build && cmake .. && make -j`nproc` decof2-example decof2-test && test/decof2-test)

after_success:
  - coveralls --include src --include include --gcov-options '\-lp'

