dist: trusty

language: cpp

compiler:
  - gcc

before_install:
  - sudo add-apt-repository -y ppa:kojoley/boost # for boost >= 1.56
  - sudo apt-get update

install:
  - sudo apt-get install g++ libboost-system1.58-dev libboost-test1.58-dev cmake-data cmake python-pip
  - sudo pip install cpp-coveralls

before_script:
  - mkdir build && cd build

script:
  - cmake .. && make -j`nproc` decof2-example decof2-test && test/decof2-test

after_success:
  - cd ..
  - coveralls --include src --include include --gcov-options '\-lp'
