dist: trusty

language: cpp

compiler:
  - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    
install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  - sudo pip install conan cpp-coveralls

before_script:
  - mkdir build && cd build
  - conan install ..

script:
  - cmake .. && make -j`nproc` decof2-example decof2-test && test/decof2-test

after_success:
  - cd ..
  - coveralls --include src --include include --gcov-options '\-lp'
