dist: xenial

language: cpp

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7 libboost-system-dev libboost-test-dev libboost-thread-dev cmake python-pip

install:
  - sudo pip install -U cpp-coveralls

before_script:
  - mkdir build

script:
  - (cd build && CC=gcc-7 CXX=g++-7 cmake .. && make -j`nproc` decof2-example decof2-test && test/decof2-test)

after_success:
  - coveralls --include src --include include --gcov-options '\-lp'
