language: cpp
compiler:
  - gcc
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test # for gcc-4.9
  - sudo add-apt-repository -y ppa:boost-latest/ppa # for boost-1.54
  - sudo add-apt-repository -y ppa:sschuberth/cmake-here # for CMake > 2.8.7
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq gcc-4.9 g++-4.9 boost1.54 cmake-data cmake doxygen python-pip
# We want to compile with g++-4.9 rather than the default g++
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90
  - sudo pip install cpp-coveralls
before_script:
  - mkdir build && cd build
script:
  - cmake .. && make && test/test
after_success:
  - cd ..
  - coveralls --gcov=gcov-4.9 --gcov-options '\-lp' --exclude build
