version: '{build}'

# Build worker image (VM template)
image: Visual Studio 2017

before_build:
  - cd ..
  - mkdir build
  - cd build
  - cmake %APPVEYOR_BUILD_FOLDER% -DBoost_INCLUDE_DIR=C:\Libraries\boost_1_69_0 -DBoost_LIBRARY_DIR=C:\Libraries\boost_1_69_0\lib64-msvc-14.1

build:
  parallel: true                # enable MSBuild parallel builds
  project: ..\build\DeCoF2.sln  # path to Visual Studio solution or project
