# Build worker image (VM template)
image: Visual Studio 2015

before_build:
  - cd ..
  - mkdir build
  - cd build
  - cmake %APPVEYOR_BUILD_FOLDER% -DBOOST_LIBRARYDIR=C:\Libraries\boost_1_60_0

build:
  parallel: true                # enable MSBuild parallel builds
  project: ..\build\DeCoF2.sln  # path to Visual Studio solution or project

